version: '3.8'

services:
  frontend:
    build:
      context: ./form
    ports:
      - "80:80"

  backend:
    build:
      context: ./node-postgres-auth
    ports:
      - "3003:3003"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=example
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5